### ISSUE TITLE
Some options don't work

### ISSUE THREAD

**Issue by ComEdEd** [CriticalFlaw/rayshud.Installer#43]
The color options work just fine health normal health buffed ect but options like transparent viewmodels chatbox on bottom 
Don't work.

**Comment by CriticalFlaw** [comment]
Are you using the latest version of the installer and a clean installation of rayshud?

If so and it's still not working, please post a screenshot of your installer settings or the log file if there was an error message.

**Comment by CriticalFlaw** [comment]
Closing due to lack of user response.
