### ISSUE TITLE
Class loadout names misaligned

### ISSUE THREAD

**Issue by milodakat** [CriticalFlaw/rayshud.Installer#45]
![image](https://user-images.githubusercontent.com/55367150/94803623-e6ab7300-042c-11eb-922d-3f1701254c39.png)
The names are misaligned, mildly frustrating but probably not much of a problem

Compare scout and soldier to see the worst of this problem.

**Comment by CriticalFlaw** [comment]
That's an issue with the Cerbetica font, because if you'll notice numbers 2-9 are all wider than 1 which causes it to look misaligned compared to the rest of them. 

Whenever I try to move it over slightly to the right it goes too far and looks misaligned the other way.
