### ISSUE TITLE
Vaccinator resistance type not displayed

### ISSUE THREAD

**Issue by ThomasHaberl** [CriticalFlaw/rayshud.Installer#46]
Updated from HUD version 3.2 to 4.2 recently. At 1440p resolution, I can no longer see the selected vaccinator resistance type:
![rays_hud](https://user-images.githubusercontent.com/22416144/95026161-9bdd6580-068f-11eb-8d91-e42ab7525d65.png)

**Comment by CriticalFlaw** [comment]
Which installer settings are you using? Preferably post a screenshot please

**Comment by CriticalFlaw** [comment]
The vaccinator resistance type is being shown correctly when you have it equipped. In your screenshot you have the Quick-Fix equipped so it wouldn't be shown for you anyway.

![20201021151305_1](https://user-images.githubusercontent.com/6818236/96771639-f248e480-13af-11eb-9e3b-6988e4166741.jpg)
