### ISSUE TITLE
Invalid Crosshair Sizes

### ISSUE THREAD

**Issue by henrythehoover** [CriticalFlaw/rayshud.Installer#47]
the crosshairs aren't working even though I have the crosshair fonts installed please help.

**Comment by henrythehoover** [comment]
> the crosshairs aren't working even though I have the crosshair fonts installed please help.

Never mind is just my crosshair was bigger  than 30

**Comment by CriticalFlaw** [comment]
It looks like the installer is still using the old available crosshair sizes where as now only sizes 10-30 are available.

**Comment by CriticalFlaw** [comment]
This issue has been fixed in version 4.4. Thank you for reporting.
